/** 
 * Creates the database used by MagusWeb (prefix MW_).
 */

/***************************************************************************
 * Table  : MW_APPLICATION
 * Purpose: Store MagusWeb generated applications. 
 ***************************************************************************/
DROP TABLE IF EXISTS MW_APPLICATION CASCADE;
CREATE TABLE MW_APPLICATION
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null, 
  name VARCHAR(80) not null,
  short_name VARCHAR(80) not null,
  description varchar(4000) null,
  path varchar(150) not null,
  copyright varchar(200),
  license_file varchar(100),
  template varchar(50),
  architecture varchar(50),
  records_per_page integer,
  user varchar(50),
  primary key(id),
  CONSTRAINT apb_uniq_name unique(name)
);

/***************************************************************************
 * Table  : APPLICATION_SERVER
 * Purpose: Store target server used in the generated application.
 ***************************************************************************/
DROP TABLE IF EXISTS MW_APPLICATION_SERVER CASCADE;
CREATE TABLE MW_APPLICATION_SERVER
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null, 
  app_id integer not null,
  folder VARCHAR(80) not null,
  manager_url varchar(150) not null,
  username varchar(20) not null,
  password varchar(20),
  primary key(id)
);

ALTER TABLE MW_APPLICATION_SERVER ADD FOREIGN KEY (app_id) REFERENCES MW_APPLICATION (ID);

/***************************************************************************
 * Table  : MW_APPLICATION_DATABASE
 * Purpose: Store target database used in the generated application.
 ***************************************************************************/
DROP TABLE IF EXISTS MW_APPLICATION_DATABASE CASCADE;
CREATE TABLE MW_APPLICATION_DATABASE
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  app_id integer not null,
  db_type varchar(30) not null,
  data_source varchar(60) not null,
  driver varchar(60) not null,
  connection_string varchar(80) not null,
  connection_impl varchar(200) not null,
  username varchar(20) not null,
  password varchar(20),
  primary key(id),
  CONSTRAINT FK_APPDAT_APP FOREIGN KEY (app_id) REFERENCES MW_APPLICATION (ID)
);



/***************************************************************************
 * Table  : MW_MENU
 * Purpose: Store menu entries for a new application.
 ***************************************************************************/
DROP TABLE IF EXISTS MW_MENU CASCADE;
CREATE TABLE MW_MENU
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  parent_menu_id integer,
  app_id integer not null,
  name VARCHAR(40) not null,
  link VARCHAR(100) null,
  primary key(id),
  CONSTRAINT FK_APPMEN_APP FOREIGN KEY (app_id) REFERENCES MW_APPLICATION (ID),
  CONSTRAINT FK_PARENTMENU_MENU FOREIGN KEY (parent_menu_id) REFERENCES MW_MENU (id)
);

/***************************************************************************
 * Table      : MW_TABLE
 * Purpose    : Store meta data information for the tables used to create a 
 *              new application.
 * Description: alias column is used for application generated code.
 * 
 *              label column is a key for i18n support (see messages files 
 *              in src/resources).
 ***************************************************************************/
DROP TABLE IF EXISTS MW_TABLE CASCADE;
CREATE TABLE MW_TABLE
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  app_id integer not null,
  catalog VARCHAR(40) not null,
  schema VARCHAR(40) not null,
  name VARCHAR(40) not null,
  alias VARCHAR(40),
  label VARCHAR(100), 
  orderby VARCHAR(40),
  export_keys boolean,
  primary key(id),
  CONSTRAINT table_uniq_name unique(app_id,name),
  CONSTRAINT FK_TAB_APP FOREIGN KEY (app_id) REFERENCES MW_APPLICATION (ID)
);
/***************************************************************************
 * Table      : MW_FIELD
 * Purpose    : Store meta data information for the tables' fields used to 
 *              create a new application.
 * Description: label column is a key for i18n support (see messages files 
 *              in src/resources).
 * 
 *              visible - 'Y' (everywhere)
 *                      - 'F' (create/update only)
 ***************************************************************************/
DROP TABLE IF EXISTS MW_FIELD CASCADE;
CREATE TABLE MW_FIELD
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  table_id integer not null,
  NAME VARCHAR(40) not null,
  label VARCHAR(100) not null,
  display_order integer,
  type integer,
  mask varchar(50),
  comment varchar(2000),
  filter char(1) default 'N',
  visible char(1) default 'Y',
  primary key(id),
  CONSTRAINT FK_FLD_TBL FOREIGN KEY (table_id) REFERENCES MW_TABLE (id),
  CONSTRAINT field_uniq_name unique(table_id,name)
);

DROP TABLE IF EXISTS MW_FIELD_OPTION CASCADE;
CREATE TABLE MW_FIELD_OPTION
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  field_id integer not null,
  value VARCHAR(40) not null,
  text VARCHAR(100) not null,
  display_order integer,
  primary key(id),
  CONSTRAINT FK_FLD_OPT_TBL FOREIGN KEY (field_id) REFERENCES MW_FIELD (id),
  CONSTRAINT field_opt_uniq_name unique(field_id,value)
);

/***************************************************************************
 * MAGUS DATA
 ***************************************************************************/

-- Keep records for default sample_employee simple application.
INSERT INTO MW_APPLICATION(name, short_name, path, template, description) VALUES ('Sample Application', 'sampleapp', 'C:/apache-tomcat-7.0.53/webapps/sampleapp', 'black', 'Sample application to test the application generator.');
INSERT INTO MW_APPLICATION_DATABASE(app_id,db_type,data_source,driver,connection_string,connection_impl,username,password) VALUES (1,'HSQLDB','ds','driver','jdbc:hsqldb:hsql://localhost/magusdb','conn_url','sa','');

