drop schema person CASCADE;
create schema person AUTHORIZATION dba;

/***************************************************************************
 * Table      : PERSON
 * Purpose    : 
 * Description: 
 ***************************************************************************/
CREATE TABLE person.PERSON
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  first_name varchar(50) not null,
  last_name varchar(50) not null,
  title varchar(50) null,
  address varchar(200) null,
  city varchar(50) null,
  state varchar(50) null,
  zip varchar(50) null,
  company varchar(50) null,
  phone_number varchar(50) null,
  email varchar(100) null,
  website varchar(200) null,
  primary key(id)
);

INSERT INTO MW_APPLICATION(ID,NAME,SHORT_NAME,DESCRIPTION,PATH,COPYRIGHT,LICENSE_FILE,TEMPLATE,ARCHITECTURE,RECORDS_PER_PAGE,USER) VALUES (30,'person','person','','/home/lestivalet/apps/apache-tomcat-8.0.41/webapps/person',null,null,'adminLTE','RESTv2',null,null);
INSERT INTO MW_APPLICATION_DATABASE(APP_ID,DB_TYPE,DATA_SOURCE,DRIVER,CONNECTION_STRING,CONNECTION_IMPL,USERNAME,PASSWORD) VALUES (30,'HSQLDB','ds','driver','jdbc:hsqldb:hsql://localhost/magusdb','connimpl','sa','');
