drop schema recipe CASCADE;
create schema recipe AUTHORIZATION dba;

/***************************************************************************
 * Table      : UNIDADE
 * Purpose    : 
 * Description: 
 ***************************************************************************/
CREATE TABLE recipe.UNIDADE
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  descricao varchar(50) not null,
  primary key(id),
  CONSTRAINT unidade_uniq_descricao unique(descricao)
);


/***************************************************************************
 * Table      : CATEGORIA
 * Purpose    : 
 * Description: 
 ***************************************************************************/
CREATE TABLE recipe.CATEGORIA
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  descricao varchar(50) not null,
  primary key(id),
  CONSTRAINT categoria_uniq_descricao unique(descricao)
);

/***************************************************************************
 * Table      : RECEITA
 * Purpose    : 
 * Description: O campo descricao serve para a pregui�a de cadastrar ingrediente por ingrediente.
 *              Derivar o preco total e calorias total baseado na lista de ingredientes
 ***************************************************************************/
CREATE TABLE recipe.RECEITA
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  categoria_id integer not null,
  nome varchar(50) not null,
  origem varchar(50) null,
  rendimento varchar(50) null,
  valor varchar(50) null,
  tempo_preparo varchar(50) null,
  nota varchar(50) null,
  fonte varchar(50) null,
  dificuldade varchar(20) null,
  descricao longvarchar null,
  modo_preparo longvarchar null,
  foto longvarbinary null,
  arquivo longvarbinary null,
  primary key(id),
  CONSTRAINT receita_uniq_nome unique(nome),
  CONSTRAINT fk_receita_categoria FOREIGN KEY (categoria_id) REFERENCES recipe.CATEGORIA (id)
);

/***************************************************************************
 * Table      : INGREDIENTE
 * Purpose    : 
 * Description: 
 ***************************************************************************/
CREATE TABLE recipe.INGREDIENTE
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  unidade_id integer null,
  nome varchar(50) not null,
  porcao varchar(50) null,
  preco decimal(10,2) null,
  calorias_porcao double null,
  primary key(id),
  CONSTRAINT ingrediente_uniq_nome unique(nome),
  CONSTRAINT fk_ingrediente_unidade FOREIGN KEY (unidade_id) REFERENCES recipe.UNIDADE (id)
);


/***************************************************************************
 * Table      : RECEITA_INGREDIENTE
 * Purpose    : 
 * Description: 
 ***************************************************************************/
CREATE TABLE recipe.RECEITA_INGREDIENTE
(
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,
  receita_id integer not null,
  ingrediente_id integer null,
  unidade_id integer null,
  quantidade varchar(50) null,
  primary key(id),
  CONSTRAINT fk_receita_ingrediente_areceita FOREIGN KEY (receita_id) REFERENCES recipe.RECEITA (id),
  CONSTRAINT fk_receita_ingrediente_ingrediente FOREIGN KEY (ingrediente_id) REFERENCES recipe.INGREDIENTE (id),
  CONSTRAINT fk_receita_ingrediente_unidade FOREIGN KEY (unidade_id) REFERENCES recipe.UNIDADE (id)
);


INSERT INTO recipe.CATEGORIA(descricao) VALUES('Bebida');
INSERT INTO recipe.CATEGORIA(descricao) VALUES('Sobremesa');
INSERT INTO recipe.CATEGORIA(descricao) VALUES('Torta');
INSERT INTO recipe.UNIDADE(descricao) VALUES('Gramas');
INSERT INTO recipe.UNIDADE(descricao) VALUES('Colher de chá');
INSERT INTO recipe.UNIDADE(descricao) VALUES('Colher de sopa');


INSERT INTO MW_APPLICATION(ID,NAME,SHORT_NAME,DESCRIPTION,PATH,COPYRIGHT,LICENSE_FILE,TEMPLATE,ARCHITECTURE,RECORDS_PER_PAGE,USER) VALUES (20,'recipe','recipe','','/home/lestivalet/apps/apache-tomcat-8.0.41/webapps/recipe',null,null,'adminLTE','RESTv2',null,null);
INSERT INTO MW_APPLICATION_DATABASE(APP_ID,DB_TYPE,DATA_SOURCE,DRIVER,CONNECTION_STRING,CONNECTION_IMPL,USERNAME,PASSWORD) VALUES (20,'HSQLDB','ds','driver','jdbc:hsqldb:hsql://localhost/magusdb','connimpl','sa','');
