<?xml version="1.0" encoding="UTF-8"?>
<classpath>
    <classpathentry kind="src" path="src/main/java"/>
    <classpathentry kind="src" path="src/test/java"/>
    <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
    <classpathentry kind="lib" path="C:/apache-tomcat-7.0.53/lib/servlet-api.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/commons-fileupload-1.3.1.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/commons-io-2.4.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/asm-all-repackaged-2.2.0-b21.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/cglib-2.2.0-b21.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/grizzly-framework-2.3.3.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/grizzly-http-2.3.3.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/grizzly-http-server-2.3.3.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/grizzly-rcm-2.3.3.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/gson-2.2.4.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/guava-14.0.1.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/hamcrest-core-1.1.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/hk2-api-2.2.0-b21.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/hk2-locator-2.2.0-b21.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/hk2-utils-2.2.0-b21.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/hsqldb.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/javax.annotation-api-1.2.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/javax.inject-2.2.0-b21.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/javax.ws.rs-api-2.0.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/jersey-client-2.5.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/jersey-common-2.5.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/jersey-container-grizzly2-http-2.4.1.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/jersey-container-servlet-core-2.5.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/jersey-server-2.5.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/jstl.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/junit-4.9.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/osgi-resource-locator-1.0.1.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/postgresql-8.4-702.jdbc4.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/standard.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/validation-api-1.1.0.Final.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/xmlpull-1.1.3.1.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/xpp3_min-1.1.4c.jar"/>
    <classpathentry kind="lib" path="WebContent/WEB-INF/lib/xstream-1.4.6.jar"/>
    <classpathentry kind="output" path="WebContent/WEB-INF/classes"/>
</classpath>
